name: variants
channels:
    - conda-forge
    - bioconda
dependencies:
    - snakemake # main # rules dependencies are on /workflow/envs
    - snakedeploy # dev
    - snakefmt # dev
    - black # dev
    - fd-find # script
    - ncbi-datasets-cli # script
